apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: wfp2_Flask_API
          image: http://192.168.0.218:32782/wfp2_flask_api:latest
          ports:
            - containerPort: 8080
