apiVersion: apps/v1
kind: Deployment
metadata:
  name: wfp2-flask-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wfp2-flask-api
  template:
    metadata:
      labels:
        app: wfp2-flask-api
    spec:
      containers:
        - name: wfp2-flask-api
          image: 192.168.0.218:32782/wfp2-flask-api:latest
          ports:
            - containerPort: 8080
