name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, linux]

    steps:
    - name: Check out code
      uses: actions/checkout@v2  

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  

    - name: Build and push Docker image
      run: |
        docker build -t 192.168.0.218:32782/wfp2_flask_api:latest .
        docker push 192.168.0.218:32782/wfp2_flask_api:latest  
  deploy:
    runs-on: [self-hosted, linux]  
    needs: build  
    steps:
    - name: Check out code
      uses: actions/checkout@v2  

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
        kubectl rollout restart deployment/wfp2_flask_api
